services:
  db:
    image: postgres:15
    env_file:
      - ${ENV_FILE}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - ${ENV_FILE}
    command: ["npm", "run", "start:prod"]

volumes:
  db-data:
